### ISSUE TITLE
No support for version higher than 4.0

### ISSUE THREAD

**Issue by abaikov** [06wj/DragonBonesJS#4]
i would like to use drogon bones js with drogonbones v4.5, but i get error "unsupported version!"

**Comment by javierlog08** [comment]
Hello Sir.
If I change all the core folder using the lasted version of official [DragonBonesJS CORE](https://github.com/DragonBones/DragonBonesJS/tree/master/DragonBones/src/dragonBones)

What any other thing I should to change? I mean ,to get this work?
Or did you create your own core?

**Comment by abaikov** [comment]
There are version field in json, generated by DragonBones, and your library (but right now i'm understand that maybe it's dragonbonesjs core) checks this version and then throw error if version lower than 4.0, but this library compatible with 4.5 dragonbones outputs. It's on this https://github.com/06wj/DragonBonesJS/blob/master/build/dragonbones-pixi.js#L5690 string. Right now i'm just write preprocessor, thats changes version field in generated json and it's work for me, but it will be nice, if you can update version value! Thanks for reply!! And sorry for my bad english!

**Comment by 06wj** [comment]
@bboyair @javierlog08    The official dragonbones now  support [pixi](https://github.com/DragonBones/DragonBonesJS/tree/master/Pixi/), you can use it directly.

**Comment by 06wj** [comment]
@bboyair I delete the version check in [v1.0.2](https://github.com/06wj/DragonBonesJS/releases/tag/v1.0.2)

**Comment by abaikov** [comment]
@06wj thanks!

**Comment by javierlog08** [comment]
@06wj  But the new Pixi support for dragon bones, from the oficial site is not working good.
Look this screenshot

https://drive.google.com/file/d/0B_CdFMs0xgtsdzdranNSeVBySGM/view

I mean, is not working good.  your project for me is also easier to understand, With it is almost posible create factories for another game engines like phaser.io for example, based on your aproach using dragon bones,  above all because there is not exist a documentation of dragon bones on english :S

**Comment by abaikov** [comment]
xDDD screenshot is awesome)))

**Comment by 06wj** [comment]
@javierlog08 The version 5.0 offcial dragonbones api has a lot of changes, I need rewrite factories, it will cost much time.  You can export v4.0 data to use my code now. I'll supoort v5.0 as soon as possible.
